In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/Datasets/simple_data.csv")

In [3]:
df.head()

sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23  Pazarlamaci     Bursa         4800

# Integer değerleri float yapalım

In [4]:
df['yas'] = df['yas'].astype(float)
df['aylik_gelir'] = df['aylik_gelir'].astype(float)

In [5]:
X = df.iloc[:,[2,5]].values
X.shape

(17, 2)

In [6]:
X

array([[   35.,  3500.],
       [   42.,  4200.],
       [   30.,  9000.],
       [   29.,  4200.],
       [   23.,  4800.],
       [   33.,  4250.],
       [   29.,  7300.],
       [   31., 12000.],
       [   33., 18000.],
       [   46., 12000.],
       [   47.,  4800.],
       [   43.,  4200.],
       [   33.,  3750.],
       [   37., 14250.],
       [   41.,  8700.],
       [   46.,  8800.],
       [   46.,  8800.]])

# 1. Standardizasyon (Feature scaling)

    preprocessing modülü ayrıca, daha sonra test setinde aynı dönüşümü tekrar uygulayabilmek için bir eğitim setindeki ortalama ve standart sapmayı hesaplamak için Transformer API'sini uygulayan bir yardımcı sınıf StandardScaler sağlar.

## 𝑋_𝑠𝑡𝑎𝑛𝑑𝑎𝑟𝑡=(𝑋 − 𝑋 ̅)/𝜎

## Niçin standardizasyon

In [7]:
import math

In [8]:
#0. vektör(35.,  3500.) ile sonuncu vektör (46.,  8800.) arasındaki mesafeyi hesaplayalım
math.sqrt( (math.pow((35 - 46),2) + (math.pow((3500 - 8800), 2)) )  )

5300.011415082046

In [9]:
# Yaşlar 0 olsaydı
math.sqrt( (math.pow((0 - 0),2) + (math.pow((3500 - 8800), 2)) )  )

5300.0

In [10]:
# Aylık gelirler 0 olsaydı
math.sqrt( (math.pow((35 - 46),2) + (math.pow((0 - 0), 2)) )  )

11.0

In [14]:
# Büyük ölçekli değişkenlerin düşük ölçekli değişkenlerin etkisini yok etmesini önlemek için.

In [11]:
from sklearn.preprocessing import StandardScaler

# Nesne oluşturma

In [12]:
scaler = StandardScaler()

# Modeli eğitme

In [13]:
scaler_model = scaler.fit(X)

# Eğitilmiş modelden dönüşüme uğramış yeni değerleri elde etme

In [14]:
X_scaled = scaler_model.transform(X)

In [15]:
X_scaled

array([[-0.23716377, -1.04075511],
       [ 0.73602551, -0.8712139 ],
       [-0.93229898,  0.29135444],
       [-1.07132602, -0.8712139 ],
       [-1.90548826, -0.72589285],
       [-0.51521786, -0.85910381],
       [-1.07132602, -0.12038851],
       [-0.79327194,  1.01795965],
       [-0.51521786,  2.47117008],
       [ 1.29213367,  1.01795965],
       [ 1.43116071, -0.72589285],
       [ 0.87505255, -0.8712139 ],
       [-0.51521786, -0.98020468],
       [ 0.04089031,  1.56291356],
       [ 0.59699847,  0.21869392],
       [ 1.29213367,  0.2429141 ],
       [ 1.29213367,  0.2429141 ]])

In [16]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-0.23716377, -1.04075511],
       [ 0.73602551, -0.8712139 ],
       [-0.93229898,  0.29135444],
       [-1.07132602, -0.8712139 ],
       [-1.90548826, -0.72589285],
       [-0.51521786, -0.85910381],
       [-1.07132602, -0.12038851],
       [-0.79327194,  1.01795965],
       [-0.51521786,  2.47117008],
       [ 1.29213367,  1.01795965],
       [ 1.43116071, -0.72589285],
       [ 0.87505255, -0.8712139 ],
       [-0.51521786, -0.98020468],
       [ 0.04089031,  1.56291356],
       [ 0.59699847,  0.21869392],
       [ 1.29213367,  0.2429141 ],
       [ 1.29213367,  0.2429141 ]])

# 0 ortalama ve 1 aryansı kontrol edelim

In [17]:
X_scaled.mean(axis=0)

array([3.39597631e-16, 3.59189802e-17])

In [18]:
#Yukarıdaki değer sıfıra çok yakındır.

In [19]:
X_scaled.std(axis=0)

array([1., 1.])

    Uygulamada genellikle dağılımın şeklini görmezden geliyoruz ve verileri her özelliğin ortalama değerini kaldırarak ortalamak için dönüştürüyoruz, ardından sabit olmayan özellikleri standart sapmalarına bölerek ölçeklendiriyoruz.

# 2. Normalizasyon

    Normalize işlevi, bu işlemi l1 veya l2 normlarını kullanarak tek bir dizi benzeri veri kümesi üzerinde gerçekleştirmek için hızlı ve kolay bir yol sağlar.

## 𝑋_𝑛𝑜𝑟𝑚=(𝑋 − 𝑋_𝑚𝑖𝑛)/(𝑋_𝑚𝑎𝑥− 𝑋_𝑚𝑖𝑛 )

In [20]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer(norm='l2')

In [21]:
normalizer_model = normalizer.fit(X)

In [22]:
X_normalized = normalizer_model.transform(X)

In [23]:
X_normalized

array([[0.0099995 , 0.99995   ],
       [0.0099995 , 0.99995   ],
       [0.00333331, 0.99999444],
       [0.0069046 , 0.99997616],
       [0.00479161, 0.99998852],
       [0.00776447, 0.99996986],
       [0.00397257, 0.99999211],
       [0.00258332, 0.99999666],
       [0.00183333, 0.99999832],
       [0.00383331, 0.99999265],
       [0.0097912 , 0.99995207],
       [0.01023756, 0.99994759],
       [0.00879966, 0.99996128],
       [0.00259648, 0.99999663],
       [0.00471259, 0.9999889 ],
       [0.0052272 , 0.99998634],
       [0.0052272 , 0.99998634]])