#  =========  Önemli Uyarı  =============
### Buradaki kodlar konuyu anlamak içindir. Şablon olarak kullanmayınız !!!

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/Datasets/simple_data.csv")

In [3]:
df.head()

sirano     isim  yas       meslek     sehir  aylik_gelir
0       1    Cemal   35         Isci    Ankara         3500
1       2    Ceyda   42        Memur   Kayseri         4200
2       3    Timur   30     Müzisyen  Istanbul         9000
3       4    Burcu   29  Pazarlamaci    Ankara         4200
4       5  Yasemin   23  Pazarlamaci     Bursa         4800

# 1. LabelEncoder

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
label_encoder = LabelEncoder()

In [6]:
meslek_encoded_model = label_encoder.fit(df['meslek'])

In [7]:
meslek_encoded = meslek_encoded_model.transform(df['meslek'])

In [9]:
meslek_encoded

array([2, 3, 4, 5, 5, 3, 5, 4, 1, 0, 7, 6, 3, 1, 4, 0, 0])

In [12]:
df['meslek_encoded'] = meslek_encoded
df.sort_values('meslek_encoded').head(17)

sirano      isim  yas       meslek     sehir  aylik_gelir  meslek_encoded
16      16    Gençay   46       Berber    Ankara         8800               0
9       10  Muhittin   46       Berber  Istanbul        12000               0
15      16    Gençay   46       Berber    Ankara         8800               0
13      14   Gülizar   37       Doktor     İzmir        14250               1
8        9     Ahmet   33       Doktor    Ankara        18000               1
0        1     Cemal   35         Isci    Ankara         3500               2
5        6       Ali   33        Memur    Ankara         4250               3
12      13     Hakkı   33        Memur     Çorum         3750               3
1        2     Ceyda   42        Memur   Kayseri         4200               3
7        8     Murat   31     Müzisyen  Istanbul        12000               4
2        3     Timur   30     Müzisyen  Istanbul         9000               4
14      15    Şehmuz   41     Müzisyen    Ankara         8700               4
6        7     Dilek   29  Pazarlamaci  Istanbul         7300               5
3        4     Burcu   29  Pazarlamaci    Ankara         4200               5
4        5   Yasemin   23  Pazarlamaci     Bursa         4800               5
11      12     Harun   43      Tornacı    Ankara         4200               6
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800               7

In [14]:
sehir_encoded_model = label_encoder.fit(df['sehir'])
sehir_encoded = meslek_encoded_model.transform(df['sehir'])
df['sehir_encoded'] = sehir_encoded
df.sort_values('sehir_encoded').head(17)

sirano      isim  yas       meslek     sehir  aylik_gelir  meslek_encoded  \
0        1     Cemal   35         Isci    Ankara         3500               2   
14      15    Şehmuz   41     Müzisyen    Ankara         8700               4   
11      12     Harun   43      Tornacı    Ankara         4200               6   
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800               7   
15      16    Gençay   46       Berber    Ankara         8800               0   
8        9     Ahmet   33       Doktor    Ankara        18000               1   
3        4     Burcu   29  Pazarlamaci    Ankara         4200               5   
5        6       Ali   33        Memur    Ankara         4250               3   
16      16    Gençay   46       Berber    Ankara         8800               0   
4        5   Yasemin   23  Pazarlamaci     Bursa         4800               5   
6        7     Dilek   29  Pazarlamaci  Istanbul         7300               5   
7        8     Murat   31     Müzisyen  Istanbul        12000               4   
9       10  Muhittin   46       Berber  Istanbul        12000               0   
2        3     Timur   30     Müzisyen  Istanbul         9000               4   
1        2     Ceyda   42        Memur   Kayseri         4200               3   
12      13     Hakkı   33        Memur     Çorum         3750               3   
13      14   Gülizar   37       Doktor     İzmir        14250               1   

    sehir_encoded  
0               0  
14              0  
11              0  
10              0  
15              0  
8               0  
3               0  
5               0  
16              0  
4               1  
6               2  
7               2  
9               2  
2               2  
1               3  
12              4  
13              5

# 2. OneHotEncoder

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
one_hot = OneHotEncoder(categories='auto')

In [29]:
one_hot_model = one_hot.fit(df[['meslek_encoded','sehir_encoded']])

In [30]:
one_hot_model

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [31]:
one_hot_all = one_hot_model.transform(df[['meslek_encoded','sehir_encoded']])

In [32]:
type(one_hot_all)

scipy.sparse.csr.csr_matrix

In [33]:
one_hot_all.toarray()

array([[0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0

In [23]:
# OneHotEncoded nitelikleri ana dataframe ile birleştirmek için dataframe'e çevirme
df_onehot = pd.DataFrame(one_hot_all.toarray())

In [24]:
# Bu yöntemle birleşme indeksler üzerinden gerçekleşir.
df_join = df.join(df_onehot, how='inner')

In [25]:
df_join.head(17)

sirano      isim  yas       meslek     sehir  aylik_gelir  meslek_encoded  \
0        1     Cemal   35         Isci    Ankara         3500               2   
1        2     Ceyda   42        Memur   Kayseri         4200               3   
2        3     Timur   30     Müzisyen  Istanbul         9000               4   
3        4     Burcu   29  Pazarlamaci    Ankara         4200               5   
4        5   Yasemin   23  Pazarlamaci     Bursa         4800               5   
5        6       Ali   33        Memur    Ankara         4250               3   
6        7     Dilek   29  Pazarlamaci  Istanbul         7300               5   
7        8     Murat   31     Müzisyen  Istanbul        12000               4   
8        9     Ahmet   33       Doktor    Ankara        18000               1   
9       10  Muhittin   46       Berber  Istanbul        12000               0   
10      11  Hicaziye   47   Tuhafiyeci    Ankara         4800               7   
11      12     Harun   43      Tornacı    Ankara         4200               6   
12      13     Hakkı   33        Memur     Çorum         3750               3   
13      14   Gülizar   37       Doktor     İzmir        14250               1   
14      15    Şehmuz   41     Müzisyen    Ankara         8700               4   
15      16    Gençay   46       Berber    Ankara         8800               0   
16      16    Gençay   46       Berber    Ankara         8800               0   

    sehir_encoded    0    1 ...     4    5    6    7    8    9   10   11   12  \
0               0  0.0  0.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
1               3  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
2               2  0.0  0.0 ...   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
3               0  0.0  0.0 ...   0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
4               1  0.0  0.0 ...   0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
5               0  0.0  0.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
6               2  0.0  0.0 ...   0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
7               2  0.0  0.0 ...   1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
8               0  0.0  1.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
9               2  1.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
10              0  0.0  0.0 ...   0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   
11              0  0.0  0.0 ...   0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0   
12              4  0.0  0.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
13              5  0.0  1.0 ...   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
14              0  0.0  0.0 ...   1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
15              0  1.0  0.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
16              0  1.0  0.0 ...   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   

     13  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  
5   0.0  
6   0.0  
7   0.0  
8   0.0  
9   0.0  
10  0.0  
11  0.0  
12  0.0  
13  1.0  
14  0.0  
15  0.0  
16  0.0  

[17 rows x 22 columns]

# LabelBinarizer: LabelEncoder ve OneHotEncoder bir arada

In [50]:
from sklearn.preprocessing import LabelBinarizer

In [51]:
lb_binarizer = LabelBinarizer()

In [52]:
lb_bin_meslek = lb_binarizer.fit_transform(df['meslek'])

In [53]:
lb_bin_meslek

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

In [54]:
lb_bin_meslek_df = pd.DataFrame(lb_bin_meslek)

In [55]:
lb_bin_meslek_df.head()

0  1  2  3  4  5  6  7
0  0  0  1  0  0  0  0  0
1  0  0  0  1  0  0  0  0
2  0  0  0  0  1  0  0  0
3  0  0  0  0  0  1  0  0
4  0  0  0  0  0  1  0  0

In [56]:
lb_bin_sehir = lb_binarizer.fit_transform(df['sehir'])

In [57]:
lb_bin_sehir 

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [58]:
# Sütun isimlerinin aynı olmaması için
lb_bin_sehir_df = pd.DataFrame(lb_bin_sehir, columns=['_0','_1','_2','_3','_4','_5'])
lb_bin_sehir_df.head()

_0  _1  _2  _3  _4  _5
0   1   0   0   0   0   0
1   0   0   0   1   0   0
2   0   0   1   0   0   0
3   1   0   0   0   0   0
4   0   1   0   0   0   0

In [59]:
df_join2 = df.join(lb_bin_meslek_df, how="inner")
df_join2.head()

sirano     isim  yas       meslek     sehir  aylik_gelir  meslek_encoded  \
0       1    Cemal   35         Isci    Ankara         3500               2   
1       2    Ceyda   42        Memur   Kayseri         4200               3   
2       3    Timur   30     Müzisyen  Istanbul         9000               4   
3       4    Burcu   29  Pazarlamaci    Ankara         4200               5   
4       5  Yasemin   23  Pazarlamaci     Bursa         4800               5   

   sehir_encoded  0  1  2  3  4  5  6  7  
0              0  0  0  1  0  0  0  0  0  
1              3  0  0  0  1  0  0  0  0  
2              2  0  0  0  0  1  0  0  0  
3              0  0  0  0  0  0  1  0  0  
4              1  0  0  0  0  0  1  0  0

In [60]:
df_join3 = df_join2.join(lb_bin_sehir_df, how="inner")
df_join3.head()

sirano     isim  yas       meslek     sehir  aylik_gelir  meslek_encoded  \
0       1    Cemal   35         Isci    Ankara         3500               2   
1       2    Ceyda   42        Memur   Kayseri         4200               3   
2       3    Timur   30     Müzisyen  Istanbul         9000               4   
3       4    Burcu   29  Pazarlamaci    Ankara         4200               5   
4       5  Yasemin   23  Pazarlamaci     Bursa         4800               5   

   sehir_encoded  0  1 ...  4  5  6  7  _0  _1  _2  _3  _4  _5  
0              0  0  0 ...  0  0  0  0   1   0   0   0   0   0  
1              3  0  0 ...  0  0  0  0   0   0   0   1   0   0  
2              2  0  0 ...  1  0  0  0   0   0   1   0   0   0  
3              0  0  0 ...  0  1  0  0   1   0   0   0   0   0  
4              1  0  0 ...  0  1  0  0   0   1   0   0   0   0  

[5 rows x 22 columns]

### Not: Gölge değişken tuzağı için endişeye gerek, yok kütüphane ilgileniyor.