## https://scikit-learn.org/stable/user_guide.html

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/Datasets/housing.csv")

# Veri Keşfi

In [3]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
df.dropna(inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20433 non-null float64
latitude              20433 non-null float64
housing_median_age    20433 non-null float64
total_rooms           20433 non-null float64
total_bedrooms        20433 non-null float64
population            20433 non-null float64
households            20433 non-null float64
median_income         20433 non-null float64
median_house_value    20433 non-null float64
ocean_proximity       20433 non-null object
dtypes: float64(9), object(1)
memory usage: 1.7+ MB


In [8]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [9]:
df = df[['ocean_proximity','longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']]

In [10]:
df.head()

ocean_proximity  longitude  latitude  housing_median_age  total_rooms  \
0        NEAR BAY    -122.23     37.88                41.0        880.0   
1        NEAR BAY    -122.22     37.86                21.0       7099.0   
2        NEAR BAY    -122.24     37.85                52.0       1467.0   
3        NEAR BAY    -122.25     37.85                52.0       1274.0   
4        NEAR BAY    -122.25     37.85                52.0       1627.0   

   total_bedrooms  population  households  median_income  median_house_value  
0           129.0       322.0       126.0         8.3252            452600.0  
1          1106.0      2401.0      1138.0         8.3014            358500.0  
2           190.0       496.0       177.0         7.2574            352100.0  
3           235.0       558.0       219.0         5.6431            341300.0  
4           280.0       565.0       259.0         3.8462            342200.0

In [16]:
X = df.iloc[:,:-1].values
X.shape

(20433, 9)

In [17]:
X[:10,:]

array([['NEAR BAY', -122.23, 37.88, 41.0, 880.0, 129.0, 322.0, 126.0,
        8.3252],
       ['NEAR BAY', -122.22, 37.86, 21.0, 7099.0, 1106.0, 2401.0, 1138.0,
        8.3014],
       ['NEAR BAY', -122.24, 37.85, 52.0, 1467.0, 190.0, 496.0, 177.0,
        7.2574],
       ['NEAR BAY', -122.25, 37.85, 52.0, 1274.0, 235.0, 558.0, 219.0,
        5.6431],
       ['NEAR BAY', -122.25, 37.85, 52.0, 1627.0, 280.0, 565.0, 259.0,
        3.8462],
       ['NEAR BAY', -122.25, 37.85, 52.0, 919.0, 213.0, 413.0, 193.0,
        4.0368],
       ['NEAR BAY', -122.25, 37.84, 52.0, 2535.0, 489.0, 1094.0, 514.0,
        3.6591],
       ['NEAR BAY', -122.25, 37.84, 52.0, 3104.0, 687.0, 1157.0, 647.0,
        3.12],
       ['NEAR BAY', -122.26, 37.84, 42.0, 2555.0, 665.0, 1206.0, 595.0,
        2.0804],
       ['NEAR BAY', -122.25, 37.84, 52.0, 3549.0, 707.0, 1551.0, 714.0,
        3.6912]], dtype=object)

In [18]:
y = df.iloc[:,-1].values
y.shape

(20433,)

In [20]:
y[:10]

array([452600., 358500., 352100., 341300., 342200., 269700., 299200.,
       241400., 226700., 261100.])

# labelEncoder

In [21]:
from sklearn.preprocessing import LabelEncoder
label_enc = LabelEncoder()

In [22]:
X[:,0] = label_enc.fit_transform(X[:,0])
X.shape

(20433, 9)

In [23]:
X[:10,:]

array([[3, -122.23, 37.88, 41.0, 880.0, 129.0, 322.0, 126.0, 8.3252],
       [3, -122.22, 37.86, 21.0, 7099.0, 1106.0, 2401.0, 1138.0, 8.3014],
       [3, -122.24, 37.85, 52.0, 1467.0, 190.0, 496.0, 177.0, 7.2574],
       [3, -122.25, 37.85, 52.0, 1274.0, 235.0, 558.0, 219.0, 5.6431],
       [3, -122.25, 37.85, 52.0, 1627.0, 280.0, 565.0, 259.0, 3.8462],
       [3, -122.25, 37.85, 52.0, 919.0, 213.0, 413.0, 193.0, 4.0368],
       [3, -122.25, 37.84, 52.0, 2535.0, 489.0, 1094.0, 514.0, 3.6591],
       [3, -122.25, 37.84, 52.0, 3104.0, 687.0, 1157.0, 647.0, 3.12],
       [3, -122.26, 37.84, 42.0, 2555.0, 665.0, 1206.0, 595.0, 2.0804],
       [3, -122.25, 37.84, 52.0, 3549.0, 707.0, 1551.0, 714.0, 3.6912]],
      dtype=object)

# OneHotEncoder

In [25]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(categorical_features=[0])

In [26]:
X = encoder.fit_transform(X).toarray()

D:\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [27]:
X.shape

(20433, 13)

In [28]:
X[:10,:]

array([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        -1.2223e+02,  3.7880e+01,  4.1000e+01,  8.8000e+02,  1.2900e+02,
         3.2200e+02,  1.2600e+02,  8.3252e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        -1.2222e+02,  3.7860e+01,  2.1000e+01,  7.0990e+03,  1.1060e+03,
         2.4010e+03,  1.1380e+03,  8.3014e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        -1.2224e+02,  3.7850e+01,  5.2000e+01,  1.4670e+03,  1.9000e+02,
         4.9600e+02,  1.7700e+02,  7.2574e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        -1.2225e+02,  3.7850e+01,  5.2000e+01,  1.2740e+03,  2.3500e+02,
         5.5800e+02,  2.1900e+02,  5.6431e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        -1.2225e+02,  3.7850e+01,  5.2000e+01,  1.6270e+03,  2.8000e+02,
         5.6500e+02,  2.5900e+02,  3.8462e+00],
       [ 0.0000e+00,  0.0000e+

# Veri setini train-test olarak ayırma (yatay bölme)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
            test_size=0.25, random_state = 142)

In [31]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(15324, 13)
(5109, 13)
(15324,)
(5109,)


# Lineer Regresyon Nesnesi Oluşturma (Boş model yaratma)

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
regressor = LinearRegression()

# Lineer modeli eğitme (modeli şekillendirme - veriye uydurma - eğitme)

In [34]:
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

# Eğitilmiş modelle (makine) test seti kullanarak tahmin 

In [35]:
y_pred = regressor.predict(X_test)

## Tahmin sonuçlarını numpy.ndarray'den dataframe yapma (İncelemek daha Kolay)

In [36]:
predictions = pd.DataFrame(data=y_pred,    # values
                index=range(len(y_pred)),    # 1st column as index
                   columns=['y_pred'])  # 1st row as the column names

# Sadece y_pred'den oluşan df'e test(gerçek) y_test'i sütun olarak ekleme
predictions['y_test'] = y_test
predictions.head()

y_pred    y_test
0  147631.839485  159400.0
1  103310.292291  119400.0
2  185856.228096  189400.0
3  278256.315362  222800.0
4  226553.607814  203500.0

# Regression metrics

## explained_variance

In [37]:
# The sklearn.metrics module implements several loss, score, and utility functions to measure 
# regression performance. Some of those have been enhanced to handle the multioutput case: 
# mean_squared_error, mean_absolute_error, explained_variance_score and r2_score.

In [38]:
from sklearn.metrics import explained_variance_score

In [39]:
explained_variance_score(y_true=y_test, y_pred=y_pred)

0.6202512479064441

## mean_absolute_error

In [40]:
from sklearn.metrics import mean_absolute_error

In [41]:
mean_absolute_error(y_true=y_test, y_pred=y_pred)

50536.09556710121

## r2_score 

In [42]:
from sklearn.metrics import r2_score

In [43]:
r2_score(y_test, y_pred)

0.6200240267207925

# Sabit ekleme

In [44]:
X.shape

(20433, 13)

In [45]:
X = np.append(arr = np.ones((20433,1)).astype(int), values = X, axis = 1)
X.shape

(20433, 14)

In [46]:
import statsmodels.formula.api as sm
X_opt = X
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()

In [47]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.646
Model:                            OLS   Adj. R-squared:                  0.646
Method:                 Least Squares   F-statistic:                     3112.
Date:                Sat, 30 Mar 2019   Prob (F-statistic):               0.00
Time:                        16:31:34   Log-Likelihood:            -2.5655e+05
No. Observations:               20433   AIC:                         5.131e+05
Df Residuals:                   20420   BIC:                         5.132e+05
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.873e+06   7.36e+04    -25.441      0.000   -2.02e+06   -1.73e+06
x1         -3.973e+05   1.55e+04    -25.676      0.000   -4.28e+05   -3.67e+05
x2         -4.366e+05   1.45e+04    -30.054      0.000   -4.65e+05   -4.08e+05
x3         -2.444e+05   2.99e+04     -8.187      0.000   -3.03e+05   -1.86e+05
x4         -4.013e+05   1.59e+04    -25.197      0.000   -4.32e+05    -3.7e+05
x5          -3.93e+05   1.58e+04    -24.835      0.000   -4.24e+05   -3.62e+05
x6         -2.681e+04   1019.651    -26.296      0.000   -2.88e+04   -2.48e+04
x7         -2.548e+04   1004.702    -25.363      0.000   -2.75e+04   -2.35e+04
x8          1072.5200     43.886     24.439      0.000     986.501    1158.540
x9            -6.1933      0.791     -7.825      0.000      -7.745      -4.642
x10          100.5563      6.869     14.640      0.000      87.093     114.019
x11          -37.9691      1.076    -35.282      0.000     -40.078     -35.860
x12           49.6173      7.451      6.659      0.000      35.012      64.222
x13         3.926e+04    338.005    116.151      0.000    3.86e+04    3.99e+04
==============================================================================
Omnibus:                     5049.292   Durbin-Watson:                   0.977
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            19123.138
Skew:                           1.197   Prob(JB):                         0.00
Kurtosis:                       7.090   Cond. No.                     5.97e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.95e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [111]:
#Her seferinde en yüksek p değerine sahip olanı silip hepsi p <= 0.05 olana kadar devam