In [1]:
import numpy as np

In [2]:
two_dim_float = np.random.rand(5,5)
print(two_dim_float)

[[0.00772426 0.54937134 0.12998277 0.27631035 0.77623205]
 [0.77644693 0.13804793 0.42182368 0.24381847 0.69275386]
 [0.30757444 0.65452774 0.58804469 0.84840376 0.72466535]
 [0.40868441 0.71049029 0.52897171 0.46709708 0.55810975]
 [0.72489935 0.8533851  0.26967063 0.24472114 0.77995157]]


# Sonuçların her defasında aynı olması için seed()

In [3]:
np.random.seed(142)
two_dim_float = np.random.rand(20,5)
print(two_dim_float)

[[0.90206152 0.55780754 0.65598471 0.83247141 0.19988419]
 [0.12725426 0.77143911 0.43228855 0.38528223 0.78364337]
 [0.78553162 0.16280861 0.11511333 0.33252155 0.60157345]
 [0.87780234 0.61487722 0.4240039  0.95784627 0.85408447]
 [0.77414528 0.87562841 0.07835524 0.03195872 0.70624246]
 [0.55297016 0.85526749 0.95410747 0.47497613 0.5481674 ]
 [0.73452535 0.53863186 0.74511416 0.57850545 0.17615075]
 [0.7574693  0.94823633 0.87774122 0.85551533 0.30142755]
 [0.10967141 0.90606606 0.91997995 0.41728586 0.02939565]
 [0.00279215 0.03273918 0.11586205 0.84782962 0.38098088]
 [0.50243638 0.46144977 0.33269178 0.42668256 0.05478812]
 [0.99436716 0.3954295  0.23951437 0.53775309 0.88952722]
 [0.57287549 0.25017651 0.3854606  0.77271445 0.35044493]
 [0.44390929 0.41410322 0.5387974  0.91819081 0.26326296]
 [0.77809458 0.59960131 0.23799241 0.53823699 0.35778167]
 [0.41327015 0.50535019 0.03588528 0.30383571 0.87276851]
 [0.99041613 0.43951434 0.81490461 0.28016241 0.07019716]
 [0.92639589 0

# Numpy çok boyutlu ndarray kesit alma

In [4]:
print(two_dim_float[:])

[[0.90206152 0.55780754 0.65598471 0.83247141 0.19988419]
 [0.12725426 0.77143911 0.43228855 0.38528223 0.78364337]
 [0.78553162 0.16280861 0.11511333 0.33252155 0.60157345]
 [0.87780234 0.61487722 0.4240039  0.95784627 0.85408447]
 [0.77414528 0.87562841 0.07835524 0.03195872 0.70624246]
 [0.55297016 0.85526749 0.95410747 0.47497613 0.5481674 ]
 [0.73452535 0.53863186 0.74511416 0.57850545 0.17615075]
 [0.7574693  0.94823633 0.87774122 0.85551533 0.30142755]
 [0.10967141 0.90606606 0.91997995 0.41728586 0.02939565]
 [0.00279215 0.03273918 0.11586205 0.84782962 0.38098088]
 [0.50243638 0.46144977 0.33269178 0.42668256 0.05478812]
 [0.99436716 0.3954295  0.23951437 0.53775309 0.88952722]
 [0.57287549 0.25017651 0.3854606  0.77271445 0.35044493]
 [0.44390929 0.41410322 0.5387974  0.91819081 0.26326296]
 [0.77809458 0.59960131 0.23799241 0.53823699 0.35778167]
 [0.41327015 0.50535019 0.03588528 0.30383571 0.87276851]
 [0.99041613 0.43951434 0.81490461 0.28016241 0.07019716]
 [0.92639589 0

In [5]:
# ilk iki sütun (0,1 indeks) tüm satırlar
print(two_dim_float[:,0:2])

[[0.90206152 0.55780754]
 [0.12725426 0.77143911]
 [0.78553162 0.16280861]
 [0.87780234 0.61487722]
 [0.77414528 0.87562841]
 [0.55297016 0.85526749]
 [0.73452535 0.53863186]
 [0.7574693  0.94823633]
 [0.10967141 0.90606606]
 [0.00279215 0.03273918]
 [0.50243638 0.46144977]
 [0.99436716 0.3954295 ]
 [0.57287549 0.25017651]
 [0.44390929 0.41410322]
 [0.77809458 0.59960131]
 [0.41327015 0.50535019]
 [0.99041613 0.43951434]
 [0.92639589 0.68892371]
 [0.13747977 0.89235468]
 [0.3933076  0.45127255]]


In [6]:
# tüm sütunlar (5-15) arası satırlar
two_dim_float[5:15,:]

array([[0.55297016, 0.85526749, 0.95410747, 0.47497613, 0.5481674 ],
       [0.73452535, 0.53863186, 0.74511416, 0.57850545, 0.17615075],
       [0.7574693 , 0.94823633, 0.87774122, 0.85551533, 0.30142755],
       [0.10967141, 0.90606606, 0.91997995, 0.41728586, 0.02939565],
       [0.00279215, 0.03273918, 0.11586205, 0.84782962, 0.38098088],
       [0.50243638, 0.46144977, 0.33269178, 0.42668256, 0.05478812],
       [0.99436716, 0.3954295 , 0.23951437, 0.53775309, 0.88952722],
       [0.57287549, 0.25017651, 0.3854606 , 0.77271445, 0.35044493],
       [0.44390929, 0.41410322, 0.5387974 , 0.91819081, 0.26326296],
       [0.77809458, 0.59960131, 0.23799241, 0.53823699, 0.35778167]])

In [36]:
# 2. satırın tüm sütunları

In [7]:
two_dim_float[2,:]

array([0.78553162, 0.16280861, 0.11511333, 0.33252155, 0.60157345])

# Matris elemanlarına erişim ve değer değiştirme

In [8]:
# 5. satırın ilk elemanı (0. indis)
two_dim_float[5][0]

0.5529701563482825

In [9]:
two_dim_float[5][0] = 0.7777701563482825

In [10]:
two_dim_float[5][0]

0.7777701563482825

# Döngülerle matris içinde dolaşma:

In [11]:
two_two = np.linspace(1,10, 10).reshape(2,5)
for i in range(two_two.shape[0]):
    for j in range(two_two.shape[1]):
        print(two_two[i][j])
        

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [12]:
# Aynı iş flat ile de yapılabilir

In [13]:
for i in two_two.flat:
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# Filtreleme

In [14]:
print(two_two)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [16]:
two_two[two_two > 5]

array([ 6.,  7.,  8.,  9., 10.])

In [22]:
ikiden_buyuk_filtre = two_two >2
print(ikiden_buyuk_filtre)

[[False False  True  True  True]
 [ True  True  True  True  True]]


In [26]:
two_two < 5

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [24]:
two_two[two_two >2]

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
two_two[two_two < 5]

array([1., 2., 3., 4.])

# reshape() Şekil değiştirme

In [45]:
y = np.random.random(16)
print(y)

[0.23157629 0.61623632 0.0340772  0.10783419 0.50222302 0.54236572
 0.01317082 0.04669455 0.82161584 0.71391049 0.57202814 0.38256664
 0.53612128 0.24153774 0.53883707 0.30521564]


In [59]:
y = y.reshape(4,4)
y

array([[0.23157629, 0.61623632, 0.0340772 , 0.10783419],
       [0.50222302, 0.54236572, 0.01317082, 0.04669455],
       [0.82161584, 0.71391049, 0.57202814, 0.38256664],
       [0.53612128, 0.24153774, 0.53883707, 0.30521564]])

In [56]:
y.shape

(4, 4)

# ravel() şekli bozmak

In [60]:
y = y.ravel()
y

array([0.23157629, 0.61623632, 0.0340772 , 0.10783419, 0.50222302,
       0.54236572, 0.01317082, 0.04669455, 0.82161584, 0.71391049,
       0.57202814, 0.38256664, 0.53612128, 0.24153774, 0.53883707,
       0.30521564])

In [58]:
y.shape

(16,)

# Horizantal stack hstack() ile array birleştirme

In [63]:
a1 = np.array([11,12,13])
a2 = np.array([21,22,23])

In [65]:
hs_a1a2 = np.hstack([a1,a2])
print(hs_a1a2)

[11 12 13 21 22 23]


# Vertical stack vstack() ile array birleştirme

In [67]:
vs_a1a2 = np.vstack([a1,a2])
print(vs_a1a2)

[[11 12 13]
 [21 22 23]]
