In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [3]:
# veri kaynağı: http://veribilimi.co/data/iris.csv
df = pd.read_csv("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/Datasets/SosyalMedyaReklamKampanyasi.csv")

# 1. Veri keşfi

In [4]:
df.head()

KullaniciID Cinsiyet  Yas  TahminiMaas  SatinAldiMi
0     15624510    Erkek   19        19000            0
1     15810944    Erkek   35        20000            0
2     15668575    Kadın   26        43000            0
3     15603246    Kadın   27        57000            0
4     15804002    Erkek   19        76000            0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
KullaniciID    400 non-null int64
Cinsiyet       400 non-null object
Yas            400 non-null int64
TahminiMaas    400 non-null int64
SatinAldiMi    400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [6]:
# Boş değer yok

In [7]:
df.describe()

KullaniciID         Yas    TahminiMaas  SatinAldiMi
count  4.000000e+02  400.000000     400.000000   400.000000
mean   1.569154e+07   37.655000   69742.500000     0.357500
std    7.165832e+04   10.482877   34096.960282     0.479864
min    1.556669e+07   18.000000   15000.000000     0.000000
25%    1.562676e+07   29.750000   43000.000000     0.000000
50%    1.569434e+07   37.000000   70000.000000     0.000000
75%    1.575036e+07   46.000000   88000.000000     1.000000
max    1.581524e+07   60.000000  150000.000000     1.000000

In [8]:
# Aykırı değer görünmüyor.

# 2. Veri Temizliği ve Ön Hazırlığı

In [9]:
# Veri önceden temizlenmiş. 
# Bu aşamada birşey yapmıyoruz.

## 2.1. Veriyi X,y olarak bölme (nitelikler matrisi ve hedef değişken - dikey bölme)

In [9]:
# hedef nitelik en sonda. -1' kadar hepsini seçiyoruz (:-1).
X = df.iloc[:,1:-1].values
X.shape

(400, 3)

In [10]:
# Kontrol
X[:3]

array([['Erkek', 19, 19000],
       ['Erkek', 35, 20000],
       ['Kadın', 26, 43000]], dtype=object)

In [11]:
# Hedef nitelik (Species) en sonda (-1)
y = df.iloc[:,-1].values
y.shape

(400,)

In [12]:
# Kontrol
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

## 2.2. Kategorik Nitelik Dönüştürme

In [22]:
# Kategorik nitelik olarak Cinsiyet ve hedef niteik var (y)

## 2.2.1. Cinsiyet için Label Encoder

In [13]:
from sklearn.preprocessing import LabelEncoder
label_encoder_cinsiyet = LabelEncoder()

In [14]:
X[:,0] = label_encoder_cinsiyet.fit_transform(X[:,0])

In [16]:
X[:3]

array([[0, 19, 19000],
       [0, 35, 20000],
       [1, 26, 43000]], dtype=object)

In [30]:
# OneHotEncoder yapmıyoruz. Çünkü binary.

In [17]:
y[:3]

array([0, 0, 0], dtype=int64)

## 2.3. Feature Scaling (Standardizasyon)

In [18]:
# Yapmak zorundayız
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [20]:
X = scaler.fit_transform(X)

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [61]:
X.shape

(400, 3)

In [21]:
X[:3]

array([[-1.02020406, -1.78179743, -1.49004624],
       [-1.02020406, -0.25358736, -1.46068138],
       [ 0.98019606, -1.11320552, -0.78528968]])

## 2.4. Veriyi eğitim ve test setlerine bölme (yatay bölme)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=142)

In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(300, 3)
(100, 3)
(300,)
(100,)


# 3. Model Oluşturma ve Eğitim

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
# minkowski: mesafe metriği
# n_neighbors: kaç komşuya bakılıp kararverilecek, tek sayı olmalı
# p: eğer minkowski seçersek hangi yöntemi olsun

In [27]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

# 4. Predictions

In [28]:
y_pred = classifier.predict(X_test)

## 4.1. Tahmin sonuçlarını numpy.ndarray'den dataframe yapma (İncelemek daha Kolay)

In [29]:
predictions = pd.DataFrame(data=y_pred,    # values
                index=range(len(y_pred)),    # 1st column as index
                   columns=['y_pred'])  # 1st row as the column names

# Sadece y_pred'den oluşan df'e test(gerçek) y_test'i sütun olarak ekleme
predictions['y_test'] = y_test
predictions.head()

y_pred  y_test
0       1       1
1       1       1
2       0       0
3       1       0
4       1       0

# 5. Model Değerlendirme

## 5.1. Hata Matrisi (Confusion Matrix)

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(cm)

[[58  9]
 [ 5 28]]


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy: % {:10.2f}".format(accuracy*100)) 
# :10.2f ifadesi ondalık kısımda iki basamak göstermek için

Accuracy: %      86.00


## 5.2. Elle Accuracy hesaplama

## 5.3. En iyi k değeri

In [34]:
# Üretilecek accuracy değerlerini toplayacağımız liste
accuracy_list = []

# k değerlerinin toplanacağı liste
k_list = []

# Arzu edilen k değerleri boyunca döngü çalıştır ve her bir k değeri için
# elde edilen accuracy skorlarını ve k değerlerini birer listede topla
for k in range(2,10):
    #sınıflandırıcı küme sayısı olarak k alıyor
    classifier = KNeighborsClassifier(n_neighbors=k, metric='minkowski', p=2)
    # Eğitim
    classifier.fit(X_train, y_train)
    # Tahmin
    y_pred = classifier.predict(X_test)
    # Accuracy skoru
    accuracy = accuracy_score(y_test, y_pred)
    # Bu döngüde elde edilen accuracy skorunu listeye ekle
    accuracy_list.append(accuracy)
    # Bu döngüde kullanılan k değerini listeye ekle
    k_list.append(k)
    # yapılan işi görmek için döngüde kullanılan k, accuracy çiftini ekrana yaz
    print("{} için accuracy: {:10.2f}".format(k,accuracy))
    
    
    
    

2 için accuracy:       0.82
3 için accuracy:       0.86
4 için accuracy:       0.86
5 için accuracy:       0.86
6 için accuracy:       0.86
7 için accuracy:       0.86
8 için accuracy:       0.86
9 için accuracy:       0.86


In [35]:
# Accuracy skorlarının bulunduğu listeden en yüksek skorun indeks numarasını al 
acc_max_index = accuracy_list.index(max(accuracy_list))
acc_max_index

1

In [36]:
# Yukarıdaki indeks k listesinde hangi k sayısına (değere) karşılık geliyorsa
# bu k değeri en iyi sonucu (accuracy) üretiyor.
k_list[acc_max_index]

3

## 5.4. En iyi k değeri için modeli eğitelim

In [37]:
# find index of max value inaccuracy_list
acc_max_index = accuracy_list.index(max(accuracy_list))
# assing this index to k_list
k = k_list[acc_max_index]
classifier = KNeighborsClassifier(n_neighbors=k, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

## 5.5. En iyi modelle tahmin yapma

In [38]:
# test setinden tahminler yapalım
y_pred = classifier.predict(X_test)

In [39]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy: % {:10.2f}".format(accuracy*100)) 
# :10.2f ifadesi ondalık kısımda iki basamak göstermek için

Accuracy: %      86.00


## 5.6. Elle tahmin seti üretme

In [62]:
tahmin_edilecek = ['Kadın',26,43000]

In [63]:
tahmin_edilecek_np = np.array(tahmin_edilecek)

In [64]:
tahmin_edilecek_np = tahmin_edilecek_np.reshape(1,3)

In [65]:
tahmin_edilecek_np.shape

(1, 3)

In [66]:
tahmin_edilecek_np

array([['Kadın', '26', '43000']], dtype='<U5')

In [67]:
tahmin_edilecek_np[:,0]

array(['Kadın'], dtype='<U5')

In [68]:
tahmin_edilecek_np[:,0] = label_encoder_cinsiyet.fit_transform(tahmin_edilecek_np[:,0])

In [69]:
tahmin_edilecek_np

array([['0', '26', '43000']], dtype='<U5')

In [70]:
tahmin_edilecek_np.shape

(1, 3)

In [71]:
tahmin_edilecek_np = scaler.fit_transform(tahmin_edilecek_np)

D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype <U5 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype <U5 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [72]:
tahmin_edilecek_np.shape

(1, 3)

In [61]:
# test seti dışında elle tahmin seti oluşturalım
X_manual_test = np.array([4.0,4.0,4.0,4.0]).reshape(1,4)

# array shape mutlaka uygun olmalı
print(X_manual_test.shape)
print(X_test.shape)

(1, 4)
(38, 4)


In [73]:
classifier.predict(tahmin_edilecek_np)

array([0], dtype=int64)