In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
# veri kaynağı: http://veribilimi.co/data/iris.csv
df = pd.read_csv("D:\\OneDrive\\egitim\\verilen\\bogazici-compec-python-ml\\Datasets\\adult_preprocessed.csv")

# 1. Veri keşfi

In [3]:
df.head()

workclass  education education_merged      marital_status  \
0         State-gov  Bachelors   Under-Graduate       Never-married   
1  Self-emp-not-inc  Bachelors   Under-Graduate  Married-civ-spouse   
2           Private    HS-grad          HS-grad            Divorced   
3           Private       11th      High-School  Married-civ-spouse   
4           Private  Bachelors   Under-Graduate  Married-civ-spouse   

          occupation   relationship   race     sex native_country  age  \
0       Adm-clerical  Not-in-family  White    Male  United-States   39   
1    Exec-managerial        Husband  White    Male  United-States   50   
2  Handlers-cleaners  Not-in-family  White    Male  United-States   38   
3  Handlers-cleaners        Husband  Black    Male  United-States   53   
4     Prof-specialty           Wife  Black  Female           Cuba   28   

     fnlwgt  education_num  capital_gain  capital_loss  hours_per_week output  
0   77516.0           13.0        2174.0           0.0            40.0  <=50K  
1   83311.0           13.0           0.0           0.0            13.0  <=50K  
2  215646.0            9.0           0.0           0.0            40.0  <=50K  
3  234721.0            7.0           0.0           0.0            40.0  <=50K  
4  338409.0           13.0           0.0           0.0            40.0  <=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45207 entries, 0 to 45206
Data columns (total 16 columns):
workclass           45207 non-null object
education           45207 non-null object
education_merged    45207 non-null object
marital_status      45207 non-null object
occupation          45207 non-null object
relationship        45207 non-null object
race                45207 non-null object
sex                 45207 non-null object
native_country      45207 non-null object
age                 45207 non-null int64
fnlwgt              45207 non-null float64
education_num       45207 non-null float64
capital_gain        45207 non-null float64
capital_loss        45207 non-null float64
hours_per_week      45207 non-null float64
output              45207 non-null object
dtypes: float64(5), int64(1), object(10)
memory usage: 5.5+ MB


In [5]:
# Boşluk yok

In [6]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  45207.00000  4.520700e+04   45207.000000  45207.000000  45207.000000   
mean      38.55018  1.897293e+05      10.118300   1101.634371     88.534298   
std       13.21845  1.056458e+05       2.552988   7507.593759    404.809784   
min       17.00000  1.349200e+04       1.000000      0.000000      0.000000   
25%       28.00000  1.173810e+05       9.000000      0.000000      0.000000   
50%       37.00000  1.783120e+05      10.000000      0.000000      0.000000   
75%       47.00000  2.379170e+05      13.000000      0.000000      0.000000   
max       90.00000  1.490400e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    45207.000000  
mean        40.937797  
std         12.007916  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [9]:
# Veri keşfi ile başka birçok groupby, count_values vb. sorgular kullanılabilir. Grafikler çizilip incelenebilr.

# 2. Veri Temizliği ve Ön Hazırlığı

In [10]:
# Veri önceden temizlenmiş olduğundan bu aşamada birşey yapmıyoruz.

## 2.1. Veriyi X,y olarak bölme (nitelikler matrisi ve hedef değişken - dikey bölme)

In [13]:
# Hedef değişken en sonda olduğu için ve sadece nümerik nitelikleri kullanacağımız için
# 9'uncu indeksten son indekse kadar tüm nitelikleri alıyoruz
X = df.iloc[:,9:-1].values
X.shape

(45207, 6)

In [14]:
# Kontrol
X[:3]

array([[3.90000e+01, 7.75160e+04, 1.30000e+01, 2.17400e+03, 0.00000e+00,
        4.00000e+01],
       [5.00000e+01, 8.33110e+04, 1.30000e+01, 0.00000e+00, 0.00000e+00,
        1.30000e+01],
       [3.80000e+01, 2.15646e+05, 9.00000e+00, 0.00000e+00, 0.00000e+00,
        4.00000e+01]])

In [15]:
# En son indeks hedef değiken (output)
y = df.iloc[:,-1].values
y.shape

(45207,)

In [16]:
# Kontrol
y[:10]

array(['<=50K', '<=50K', '<=50K', '<=50K', '<=50K', '<=50K', '<=50K',
       '>50K', '>50K', '>50K'], dtype=object)

## 2.2. Kategorik Nitelik Dönüştürme

### 2.2.1. Hedef değişken için Label Encoder

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
# Hedef niteliği sadece LabelEncoder ile rakamlara kodluyoruz.
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

## 2.3. Feature Scaling (Standardizasyon)

In [19]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [21]:
# Kontrol
X[:3]

array([[ 0.03403006, -1.06217677,  1.12876813,  0.14283904, -0.21870834,
        -0.07809912],
       [ 0.86620945, -1.00732307,  1.12876813, -0.14673764, -0.21870834,
        -2.32664074],
       [-0.04162261,  0.24531959, -0.43804067, -0.14673764, -0.21870834,
        -0.07809912]])

## 2.4. Veriyi eğitim ve test setlerine bölme (yatay bölme)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=142)

In [24]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(33905, 6)
(33905,)
(11302, 6)
(11302,)


# 3. Model Oluşturma ve Eğitim

In [25]:
from sklearn.linear_model import LogisticRegression

In [28]:
classifier = LogisticRegression(random_state=142, solver='lbfgs')

In [29]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

# 4. Predictions

In [30]:
y_pred = classifier.predict(X_test)

## 4.1. Tahmin sonuçlarını numpy.ndarray'den dataframe yapma (İncelemek daha Kolay)

In [31]:
predictions = pd.DataFrame(data=y_pred,    # values
                index=range(len(y_pred)),    # 1st column as index
                   columns=['y_pred'])  # 1st row as the column names

# Sadece y_pred'den oluşan df'e test(gerçek) y_test'i sütun olarak ekleme
predictions['y_test'] = y_test
predictions.head()

y_pred  y_test
0       0       0
1       0       0
2       0       0
3       0       0
4       0       0

# 5. Model Değerlendirme

## 5.1. Hata Matrisi (Confusion Matrix)

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
cm = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(cm)

[[8002  483]
 [1755 1062]]


## 5.2. Sınıflandırma Performansı Değerlendirme (Accuracy)

In [34]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy: % {:10.2f}".format(accuracy*100)) 
# :10.2f ifadesi ondalık kısımda iki basamak göstermek için

Accuracy: %      80.20


## 5.3. Elle Accuracy hesaplama

In [37]:
predictions[predictions['y_pred'] != predictions['y_test']].head()

y_pred  y_test
7        1       0
9        0       1
12       1       0
44       0       1
46       1       0

In [50]:
errors_ps_series = predictions[predictions['y_pred'] != predictions['y_test']].count()

In [51]:
error_count = errors_ps_series.get_values()[0]
error_count

2238

In [52]:
len(y_test)

11302

In [53]:
accuracy = (len(y_test) - error_count) / len(y_test)
accuracy

0.8019819500973279

# 6. Modeli Saklama ve Tekrar Kullanma

In [57]:
# Saklamadan önce tüm veri seti ile modeli tekrar eğitelim

## 6.1. Tüm veri ile modeli son olarak eğitme

In [58]:
# Eğitim setlerinin X ve y olduğuna dikkat!!!
classifier_last = LogisticRegression(random_state=142, solver='lbfgs')
classifier_last.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [59]:
# Çalışırlığının basit kontrolü. Modeli tekrar okuduktan sonra bu değerle karşılaştırma yapacağız.
classifier_last.intercept_

array([-1.28198704])

## 6.2. Modeli kaydetme

In [60]:
from sklearn.externals import joblib

In [61]:
# joblib.dump(sınıflandırıcı, "/dizin/saklamak_istedigimiz_isim.pkl")
joblib.dump(classifier_last, 
"D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/08_classification/saved_models/03.logistic_regression_with_adult_just_numeric.pkl")

['03.logistic_regression_with_adult_just_numeric.pkl']

In [62]:
# Kaydedilen yere Dosya gezgini veya jupyter home'dan bir göz atalım.

## 6.3. Modeli okuma

In [63]:
classifier_last_loaded = joblib.load("D:/OneDrive/egitim/verilen/bogazici-compec-python-ml/08_classification/saved_models/03.logistic_regression_with_adult_just_numeric.pkl")

In [64]:
classifier_last_loaded.get_params

<bound method BaseEstimator.get_params of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=142, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)>

In [65]:
classifier_last_loaded.intercept_

array([-1.28198704])